// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.learn.computation.models;

import com.azure.core.exception.HttpResponseException;
import com.azure.core.http.HttpResponse;

/** Exception thrown for an invalid response with ComputeError information. */
public final class ComputeErrorException extends HttpResponseException {
    /**
     * Initializes a new instance of the ComputeErrorException class.
     *
     * @param message the exception message or the response content if a message is not available.
     * @param response the HTTP response.
     */
    public ComputeErrorException(String message, HttpResponse response) {
        super(message, response);
    }

    /**
     * Initializes a new instance of the ComputeErrorException class.
     *
     * @param message the exception message or the response content if a message is not available.
     * @param response the HTTP response.
     * @param value the deserialized response value.
     */
    public ComputeErrorException(String message, HttpResponse response, ComputeError value) {
        super(message, response, value);
    }

    @Override
    public ComputeError getValue() {
        return (ComputeError) super.getValue();
    }
}
