// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.learn.computation.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for ComputeOperationStatus. */
public final class ComputeOperationStatus extends ExpandableStringEnum<ComputeOperationStatus> {
    /** Static value notstarted for ComputeOperationStatus. */
    public static final ComputeOperationStatus NOTSTARTED = fromString("notstarted");

    /** Static value running for ComputeOperationStatus. */
    public static final ComputeOperationStatus RUNNING = fromString("running");

    /** Static value succeeded for ComputeOperationStatus. */
    public static final ComputeOperationStatus SUCCEEDED = fromString("succeeded");

    /** Static value failed for ComputeOperationStatus. */
    public static final ComputeOperationStatus FAILED = fromString("failed");

    /** Static value cancelled for ComputeOperationStatus. */
    public static final ComputeOperationStatus CANCELLED = fromString("cancelled");

    /**
     * Creates or finds a ComputeOperationStatus from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding ComputeOperationStatus.
     */
    @JsonCreator
    public static ComputeOperationStatus fromString(String name) {
        return fromString(name, ComputeOperationStatus.class);
    }

    /** @return known ComputeOperationStatus values. */
    public static Collection<ComputeOperationStatus> values() {
        return values(ComputeOperationStatus.class);
    }
}
