// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.learn.computation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The LinuxComputeNode model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("LinuxComputeNode")
@Fluent
public final class LinuxComputeNode extends ComputeNode {
    /*
     * The compute node's public key
     */
    @JsonProperty(value = "sshPublicKey", required = true)
    private String sshPublicKey;

    /**
     * Creates an instance of LinuxComputeNode class.
     *
     * @param sshPublicKey the sshPublicKey value to set.
     */
    @JsonCreator
    public LinuxComputeNode(@JsonProperty(value = "sshPublicKey", required = true) String sshPublicKey) {
        this.sshPublicKey = sshPublicKey;
    }

    /**
     * Get the sshPublicKey property: The compute node's public key.
     *
     * @return the sshPublicKey value.
     */
    public String getSshPublicKey() {
        return this.sshPublicKey;
    }
}
