// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.learn.computation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The WindowsComputeNode model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("WindowsComputeNode")
@Fluent
public final class WindowsComputeNode extends ComputeNode {
    /*
     * The Windows user name
     */
    @JsonProperty(value = "userName", required = true)
    private String userName;

    /**
     * Creates an instance of WindowsComputeNode class.
     *
     * @param userName the userName value to set.
     */
    @JsonCreator
    public WindowsComputeNode(@JsonProperty(value = "userName", required = true) String userName) {
        this.userName = userName;
    }

    /**
     * Get the userName property: The Windows user name.
     *
     * @return the userName value.
     */
    public String getUserName() {
        return this.userName;
    }
}
