// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.learn.computation.implementation.models;

import com.azure.core.annotation.Fluent;
import com.azure.learn.computation.models.ComputeNode;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The PageOfComputeNodes model. */
@Fluent
public final class PageOfComputeNodes {
    /*
     * The compute nodes in this page
     */
    @JsonProperty(value = "value", required = true)
    private List<ComputeNode> value;

    /*
     * The opaque URL to retrieve the next page
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Creates an instance of PageOfComputeNodes class.
     *
     * @param value the value value to set.
     */
    @JsonCreator
    public PageOfComputeNodes(@JsonProperty(value = "value", required = true) List<ComputeNode> value) {
        this.value = value;
    }

    /**
     * Get the value property: The compute nodes in this page.
     *
     * @return the value value.
     */
    public List<ComputeNode> getValue() {
        return this.value;
    }

    /**
     * Get the nextLink property: The opaque URL to retrieve the next page.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: The opaque URL to retrieve the next page.
     *
     * @param nextLink the nextLink value to set.
     * @return the PageOfComputeNodes object itself.
     */
    public PageOfComputeNodes setNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
